AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    Environment:
      Variables:
        DDB_TABLE: MediaTags
        RAW_BUCKET: !Ref RawBucket
        THUMB_BUCKET: !Ref ThumbBucket
        SNS_TOPIC_ARN: arn:aws:sns:ap-southeast-2:123456789012:NewBirdUploads


Resources:
  RawBucket:
    Type: AWS::S3::Bucket

  ThumbBucket:
    Type: AWS::S3::Bucket

  MediaTagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MediaTags
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: fileId
        AttributeType: S
      KeySchema:
      - AttributeName: fileId
        KeyType: HASH

  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/generate_thumbnail.lambda_handler
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref RawBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .jpg

  TaggingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/tag_file.lambda_handler
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref RawBucket
            Events: s3:ObjectCreated:*
      Policies:
      - SNSPublishMessagePolicy:
          TopicName: NewBirdUploads

  QueryByCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/query_by_count.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /search/by-count
            Method: post

  QueryByTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/query_by_tag.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /search/by-tag
            Method: get

  LookupOriginalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/lookup_original.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /lookup/original
            Method: get

  QueryByFileTagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/query_by_file_tags.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /search/by-file-tags
            Method: post

  BulkTagUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/bulk_tag_update.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tags/bulk-update
            Method: post

  DeleteFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/delete_files.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /files
            Method: delete

Outputs:
  ApiUrl:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
    Description: "API  URL"
